# Generated by Django 3.2 on 2023-12-14 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_name', models.CharField(help_text='必需', max_length=255, verbose_name='交易方式')),
                ('delivery_method', models.CharField(choices=[('IS', '自取'), ('HD', '上门'), ('DD', '电子方式')], help_text='必需', max_length=255, verbose_name='delivery_method')),
                ('delivery_timeframe', models.CharField(help_text='必需', max_length=255, verbose_name='delivery timeframe')),
                ('delivery_window', models.CharField(help_text='必需', max_length=255, verbose_name='delivery window')),
                ('delivery_price', models.DecimalField(blank=True, decimal_places=1, help_text='交付价格', max_digits=3, null=True, verbose_name='delivery price')),
                ('order', models.IntegerField(default=0, help_text='必需', verbose_name='list order')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '选项',
                'verbose_name_plural': '选项',
            },
        ),
        migrations.CreateModel(
            name='PaymentSelections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='必需', max_length=255, verbose_name='name')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '支付选项',
                'verbose_name_plural': '支付选项',
            },
        ),
    ]
