# Generated by Django 3.2 on 2023-12-14 21:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required and unique', max_length=255, unique=True, verbose_name='类别名')),
                ('brief', models.CharField(max_length=1000, null=True, verbose_name='类别简介')),
                ('slug', models.SlugField(help_text='在网页中定位到商品的唯一英文字符', max_length=255, unique=True, verbose_name='安全URL')),
                ('is_active', models.BooleanField(default=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalogue.category')),
            ],
            options={
                'verbose_name': '类别',
                'verbose_name_plural': '类别',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Required', max_length=255, verbose_name='名称')),
                ('quantity', models.IntegerField(default=1, error_messages={'name': {'max_length': '数量必须在 0 和 99 之间'}}, help_text='若REQ与数量有关,则填写(默认为1)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='数量')),
                ('description', models.TextField(blank=True, help_text='添加REQ描述（选填）', verbose_name='描述')),
                ('regular_price', models.DecimalField(decimal_places=2, error_messages={'name': {'max_length': '悬赏必须在 0 和 999.99 之间'}}, help_text='最多 9999.99 元', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='悬赏金额')),
                ('is_active', models.BooleanField(default=True, verbose_name='REQ是否可见：')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalogue.category', verbose_name='类别')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='selling_product', to=settings.AUTH_USER_MODEL)),
                ('users_wishlist', models.ManyToManyField(blank=True, related_name='user_wishlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'REQ',
                'verbose_name_plural': 'REQ',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='images/default.png', upload_to='images/', verbose_name='图片')),
                ('alt_text', models.CharField(blank=True, help_text='请添加图片的描述信息', max_length=255, null=True, verbose_name='描述信息')),
                ('is_feature', models.BooleanField(default=False, verbose_name='是否展示')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='catalogue.product')),
            ],
            options={
                'verbose_name': 'REQ的图片',
                'verbose_name_plural': 'REQ的图片',
            },
        ),
    ]
